[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Markiz"]
requires-python = ">=3.11"
dependencies = [
    "chess>=1.11.2",
    "python-lichess>=0.10",
    "requests>=2.32.3",
]
